### ISSUE TITLE
Problème mail

### ISSUE THREAD

**Issue by legalb0r** [N7-Consulting/Incipio#354]
Bonjour,

Je suis DSI de la juniorUTC, nous utilisons jeyser depuis quelques semestres.

### Problème mail

Je rencontre un problème de mail. Les mails d'envoi de confirmation lors de la création de compte, ou de changement de mot de passe ne sont pas envoyés.

Comment se passe cet envoi de mail normalement, et ou est ce codé?

Est ce un problème récurent et si oui quelles solutions sont directement envisageables?

### Problème documentation

Ce problème concerne la documentation, les liens sur jeyser-crm.n7consulting.fr renvoient des liens locaux ce qui complique la navigation (erreur 404, forcement, et donc on doit copier le début de l'adresse à la main). 

Merci !

**Comment by Stoakes** [comment]
Bonjour,

L'envoi de mail est inclus dans le FosUserBundle. Jeyser ne le contrôle pas directement, je ne peux donc pas te pointer vers le code. 
La configuration de l'envoi de mail est paramétrée par la variable d'environnement `MAILER_URL` dans le fichier `.env` à la racine du dossier Jeyser.
Par défaut les mails sont envoyés via le serveur postfix tournant dans le container `mailer`. Ca se passe généralement bien, même si c'est un problème connu que certaines installations n'arrivent pas à envoyer des mails. Notamment vers hotmail, j'ai vu ça plusieurs fois.

La source probable du problème est que votre serveur n'est pas reconnu comme fiable par les systèmes de messagerie, donc les mails de Jeyser sont filtrés comme spam. Dans certains cas ils sont tout simplement rejetés.

Il existe une solution de contournement, mais elle n'est documentée nulle part. Au lieu de passer par le postfix local pour envoyer des mails, il est possible d'envoyer des mails via un fournisseur externe. [Mailjet](https://fr.mailjet.com/) par exemple.

Une fois votre compte Mailjet créé, le site vous guidera à travers d'une série d'étape pour configurer des enregistrements DMARC et DKIM. Puis vous pourrez récupérer des identifiants pour envoyer des mails via SMTP.

Editez le fichier `.env`pour remplacer `MAILER_URL=smtp://mailer:25` part `MAILER_URL=smtp://user:password@in-v3.mailjet.com:587`. 
Puis recréez le container de Jeyser: `docker-compose up -d` et normalement ça devrait fonctionner.
Essayez d'envoyer quelques mails et vous devriez les voir passer depuis le panneau d'admin Mailjet.

**Comment by Stoakes** [comment]
Merci pour le commentaire sur les liens de la documentation.

Je viens de corriger ça, https://github.com/n7consulting/jeyser-site/pull/8, ça devrait être déployé prochainement.

**Comment by Stoakes** [comment]
Et voilà ! https://jeyser-crm.n7consulting.fr/docs/install/use-different-email-sender/ testé sans problème sur une installation perso, donc ça devrait marcher chez vous.

Encore merci pour vos commentaires.

Toutes les remarques ont été adressées, donc je clôture ce ticket. N'hésitez toutefois pas à commenter ici si vous avez d'autres commentaires sur le même sujet. Si vous avez d'autres questions, vous pouvez ouvrir un autre ticket.

A bientôt
